apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: url-app
  name: url-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-app
  template:
    metadata:
      labels:
        app: url-app
    spec:
      containers:
      - image: ch316/guniflask
        name: guniflask
        ports:
         - name: http
           containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: url-app
  name: url-app
spec:
  ports:
  - name: url-app
    port: 8321
    protocol: TCP
    targetPort: 8000
  selector:
    app: url-app
  type: NodePort
